language: node_js
node_js:
  - "stable"

notifications:
  email:
    if: branch = release
    on_success: always
    on_failure: always

cache:
  directories:
  - node_modules

stages:
  - test
  - name: build
    if: branch = release

jobs:
  include:
    - stage: test
      script:
        - echo "No tests yet"
        # - yarn test
    - stage: build
      script: ./scripts/build.sh
